config/routes.rb
Timesheets::Application.routes.draw do
  get "team/index"

  devise_for :users
  resources :users,:organizations, :time_entries ,:projects, :clients

  root :to=>"home#index"

  match '/projects' => 'projects#index'

  match '/clients' => 'clients#index'

  get '/reports'	=> 'reports#index'

  get '/team' => 'team#index'
  post '/team' => 'team#create', :as=>:create_member

  get '/reports/:id/monthly_report' => 'reports#monthly_report' ,as: :monthlyreport

  get '/reports/:id/yearly_report' => 'reports#yearly_report' , as: :yearlyreport

  get '/reports/:id/user_efforts_report' => 'reports#user_efforts_report', as: :userefforts

  get '/reports/:id/client_monthly_report' => 'reports#client_monthly_report', as: :clientsreport

   


  







end

app/models/time_entry.rb
class TimeEntry < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
  belongs_to :organization
  
  attr_accessible :billable, :description, 
  				  :minutes , :effective_date,
  				  :project_id, :user_id
end

app/controllers/time_entries_controller.rb
class TimeEntriesController < ApplicationController
	before_filter :authenticate_user!, :ensure_user_organization, :timeentry_organization
	
	

	def index
		@time_entry= TimeEntry.new
		@time_entries = @organization.time_entries if current_user.is_admin?
		@time_entries ||= current_user.time_entries
		
	end


	
	respond_to :html, :xml, :json

	def create

		@time_entry= TimeEntry.new(params[:time_entry])
		@time_entry.organization = @org_id
		@time_entry.user_id = current_user.id

		if @time_entry.save
			respond_with do |format|
      			format.html do
      			if request.xhr?
					render @time_entry
				else
					redirect_to time_entries_path
				end
				end
			end
		else
			respond_with do |format|
			format.html do
				if 	request.xhr?
					render :html => @time_entry.errors, :notice => "Unprocessable entity"
				else
					render :action => "index" , :notice => "Timeentry is not added"
				end
			end
			end
		
		end
	end


		

	
	def edit
		@time_entry= TimeEntry.find(params[:id])
		@remote = request.xhr?
		if(@remote)
			render :partial=>"time_entry_form", :locals=>{time_entry: @time_entry, remote: @remote}
			return
		end
	end

	def update

	 @time_entry = TimeEntry.find(params[:id])

      if @time_entry.update_attributes(params[:time_entry])
	        respond_with do |format|
      			format.html do
      			if request.xhr?
					render @time_entry
				else
					redirect_to @time_entry
				end
				end
			end
		else
			respond_with do |format|
			format.html do
				if 	request.xhr?
					render :html => @time_entry.errors, :notice => "Unprocessable entity"
				else
					render :action => "index" , :notice => "Timeentry is not added"
				end
			end
			end
		
		end
	end


	


	




	private 
	def ensure_user_organization
		if user_signed_in? 
	  	if current_user.organization.nil?
	  		redirect_to new_organization_path
	  		return
	  	end
	  end
	 end

	def timeentry_organization
		@org_id=current_user.organization
		@organization=Organization.find(@org_id)

	end
	




end

app/helpers/time_entries_helper.rb
module TimeEntriesHelper
end

app/views/time_entries/_time_entry.html.erb
		<div class="time_entry row">
		  <div class="minutes span2"> <%= time_entry.minutes %></div>
		  <div class="project span2">
		  	<%= link_to time_entry.project.name, edit_time_entry_path(current_user.id)  %> </div>
		  <div class="description span2"><%= time_entry.description %>
		  </div>

		  <div class="date span2"> <%= time_entry.effective_date %> </div>
		  <% if current_user.is_admin? %>
		  <div class="email span2"> <%= time_entry.user.email if time_entry.user %> 
		  </div>
		  <% end %>
		  <div class="edit span2">
		  	<%= link_to 'edit', edit_time_entry_path(time_entry), :class=>"edit-time-entry btn"%>
		  </div>
		</div>
		

app/views/time_entries/_time_entry_form.html.erb
<%=simple_form_for time_entry, :remote=>remote do |f|%>
<div class="row">
	<div class="span2">
		<%= f.input :minutes %>
	</div>
	<div class="span2">
		<%= f.input :project_id, collection: Project.all, :label_method=>:name, :value_method=>:id %>
	</div>
	<div class="span3">
		<%= f.input :description, :as=>:string %>
	</div>
	<div class="span3">
		<%= f.input :effective_date, as: :date %>
	</div>
	<%#= f.input :user_id, as: :hidden, :input_html=>{value: current_user.id}	%>
	<div class="span2">
		<%= f.submit %>
	</div>
</div>	
<% end %>	

app/views/time_entries/edit.html.erb
<%= render :partial=>"time_entry_form", :locals=>{:time_entry=>@time_entry, :remote=>@remote} %>

app/views/time_entries/index.html.erb
<%= render :partial=>"time_entry_form", :locals=>{:time_entry=>@time_entry, :remote=>true} %>
<div id="timeentries"></div>
<div class="time row">
  <%= render @time_entries %>
</div>