config/routes.rb
Timesheets::Application.routes.draw do
  get "team/index"

  devise_for :users
  resources :users,:organizations, :time_entries ,:projects, :clients

  root :to=>"home#index"

  match '/projects' => 'projects#index'

  match '/clients' => 'clients#index'

  get '/reports'	=> 'reports#index'

  get '/team' => 'team#index'
  post '/team' => 'team#create', :as=>:create_member

  get '/reports/:id/monthly_report' => 'reports#monthly_report' ,as: :monthlyreport

  get '/reports/:id/yearly_report' => 'reports#yearly_report' , as: :yearlyreport

  get '/reports/:id/user_efforts_report' => 'reports#user_efforts_report', as: :userefforts

  get '/reports/:id/client_monthly_report' => 'reports#client_monthly_report', as: :clientsreport

   


  







end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.is_admin?
        can :manage, :all
    else
        can :read, :all
    end
  end
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  attr_accessible :description

  belongs_to :project
end

app/models/client.rb
class Client < ActiveRecord::Base
  attr_accessible :client_name,:project_id,:organization_id

   has_many :projects
   belongs_to :organization
   
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  attr_accessible :name, :created_user_id
  has_many :users
  has_many :time_entries
  has_many :clients
  belongs_to :created_user, :class_name=>"User", :foreign_key=>:created_user_id

  validates_presence_of :name
end

app/models/project.rb
class Project < ActiveRecord::Base
  
  belongs_to :client
  has_many :time_entries
  has_many :activities
  

  attr_accessible :name , :client_id


  end

app/models/time_entry.rb
class TimeEntry < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
  belongs_to :organization
  
  attr_accessible :billable, :description, 
  				  :minutes , :effective_date,
  				  :project_id, :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  
  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me, :organization_id
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable
         #, :trackable

         #, :validatable

  # attr_accessible :title, :body
  # after_create :send_email
  belongs_to :organization
  has_many :time_entries , order: 'effective_date desc'
  has_many :projects

  def send_email
    Notifier.welcome_email(self).deliver
  end

  def is_admin?
    self.organization.created_user_id==self.id
  end
  
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

before_filter :authenticate_user!, :client_organization

def index

@client= Client.new

@clients=@organization1.clients

end

def create

	@client= Client.new(params[:client].merge(:organization_id=>current_user.organization_id))



	if @client.save
		
		

		redirect_to clients_path, :notice => "New client created successfully"

	else 

		redirect_to clients_path, :notice => "Client not created "
	end
end


def client_organization
		@org_id=current_user.organization_id
		@organization1=Organization.find(@org_id)

	end
	




end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		if user_signed_in?
			redirect_to time_entries_path
			
		end
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
before_filter :authenticate_user! 

def index

@project= Project.new

@client=current_user.clients

@projects = @client.projects

end

def create

	@project= Project.new(params[:project])

	if @project.save
		
		redirect_to projects_path, :notice => "New projects created successfully"

	else 

		redirect_to projects_path, :notice => "Project not created "
	end
end



end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

def index
@time_reports=Project.all
@clients=Client.all

end

def monthly_report
		#@q="select t.effective_date,t.minutes, p.name, t.description  from time_entries t, projects p where t.project_id=p.id group by name order by effective_date;"
		

			#@query ="SELECT t.effective_date,t.minutes,p.name from time_entries t, projects p where t.project_id=p.id   order by effective_date desc ;"
		
		#effort_id=params[:effort_id]

     
		@efforts=TimeEntry.select("sum(minutes) minutes,strftime('%Y-%m-%d',effective_date),user_id ,effective_date, project_id").where("project_id = ? and organization_id =? ", params[:id],current_user.organization).group("strftime('%Y-%m-%d',effective_date),project_id").includes(:project)
		@report_months=@efforts.group_by{ |m| m.effective_date.beginning_of_month}
		
		#@report_years=@reports.group_by{|y| y.effective_date.beginning_of_year }

	end

def yearly_report

	@reports=TimeEntry.joins('LEFT OUTER JOIN projects ON projects.id = time_entries.project_id').where("project_id = ?", params[:id])
	@report_years=@reports.group_by{ |m| m.effective_date.beginning_of_month}
	
	
	end

def user_efforts_report
	@efforts=TimeEntry.select("sum(minutes) minutes,strftime('%Y-%m-%d',effective_date),user_id ,effective_date, project_id").where("project_id = ? and organization_id =? ", params[:id],current_user.organization).group("strftime('%Y-%m-%d',effective_date),project_id,user_id").includes(:project, :user)
	@user_efforts=@efforts.group_by{ |m| m.effective_date.beginning_of_month}

end

def client_monthly_report
	@efforts_to_client=TimeEntry.select("sum(minutes) minutes,strftime('%Y-%m-%d',effective_date),user_id ,effective_date, client_id").where("client_id = ? and organization_id =? ", params[:id],current_user.organization).group("strftime('%Y-%m-%d',effective_date),client_id").includes(:project => :client)
	@monthly_efforts_to_client=@efforts_to_client.group_by{ |m| m.effective_date.beginning_of_month}

end


end

app/controllers/team_controller.rb
class TeamController < ApplicationController
  before_filter :authenticate_user!
	

	  def index
		  	@user=User.new
		  	@team=User.all
	  end

	  
	def create
    @user = User.new(params[:user].merge(:password=>"password", 
    									 :password_confirmation=>"password",
    									 :organization_id=>current_user.organization_id))

	    if @user.save
	          respond_to do |format|
	           format.html { redirect_to team_path }
	       		end
	    else
	      respond_to do |format| 
	        format.xml  { head :ok }
	        format.html { render :team_path ,:status => :unprocessable_entity }
	      end
	    end

	end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/time_entries_helper.rb
module TimeEntriesHelper
end

app/views/home/index.html.erb
<h1>Timesheets</h1>

app/views/reports/client_monthly_report.html.erb
<br>
<h2> Monthly Report </h2>

	<% @monthly_efforts_to_client.keys.sort.each do |month,year| %>
		<h3><%= month.strftime('%B-%Y') %></h3>
		<% @mins=0 %>
		<% @same_date='1987-04-01' %>
		<% @same_project="default" %>


	<% @monthly_efforts_to_client[month].each do |report|%>

	
		
		
			<div class="report_entry row">
			<div class="date span2"> <%= report.effective_date %></div>
			<div class="workedhours span2"> <%= report.minutes  %>  </div>
			<div class="minutes span2"> <%= report.client.client_name %></div>
			<div class="minutes span2"> <%= report.project.name %></div>

			</div>
		

	<% end %>

<% end %>
		

app/views/reports/index.html.erb
<br>

<h1> Report for Projects </h1>

<br>
<% @time_reports.each do |time_report| %>
	<div class="report_entry">
		<b><%= time_report.name %></b> 

		<%= link_to "Monthly Reports", monthlyreport_path(time_report) %>
		<%= link_to "Yearly Reports",yearlyreport_path(time_report) %>
		<%= link_to "Employee efforts",userefforts_path(time_report) %>
	<div>
	
<%end %>


<br>
	<h1> Report for Clients </h1>
<br>
<% @clients.each do |client| %>
	<div class="report_entry">
		<b><%= client.client_name %></b> 

		<%= link_to "Monthly Reports", clientsreport_path(client) %>
		
	<div>


<%end %>

app/views/reports/monthly_report.html.erb
<br>
<h2> Monthly Report </h2>

	<% @report_months.keys.sort.each do |month,year| %>
		<h3><%= month.strftime('%B-%Y') %></h3>
		<% @report_months[month].each do |report|%>

		<%  @same_date=report.effective_date %>
		<% @same_project=report.project.name %>
		
		
			<div class="report_entry row">
			<div class="date span2"> <%= report.effective_date %></div>
			<div class="workedhours span2"> <%= report.minutes  %>  </div>
			<div class="minutes span2"> <%= report.project.name %></div>


			</div>
		

	<% end %>

<% end %>
		

app/views/reports/user_efforts_report.html.erb
<br>
<h2> User efforts </h2>

	<% @user_efforts.keys.sort.each do |month,year| %>
		<h3><%= month.strftime('%B-%Y') %></h3>
		<% @mins=0 %>
		<% @same_date='1987-04-01' %>
		<% @same_project="default" %>


	<% @user_efforts[month].each do |report|%>

		<%  @same_date=report.effective_date %>
		<% @same_project=report.project.name %>
		
		
			<div class="report_entry row">
			<div class="date span2"> <%= report.effective_date %></div>
			<div class="workedhours span2"> <%= report.minutes  %>  </div>
			<div class="minutes span2"> <%= report.project.name %></div>
			<div class="minutes span2"> <%= report.user.email %></div>


			</div>
		

	<% end %>

<% end %>
		

app/views/reports/yearly_report.html.erb
<br>
<h2> Yearly Report </h2>



<% @report_years.keys.sort.each do |month,year| %>

<h3><%= month.strftime('%Y-%B') %></h3>
	<% @mins=0 %>
	<% @month_mins=0 %>

		<% @report_years[month].each do |report| %>
			<% @projectname=report.project.name %>
			<% @mins=report.minutes %>
			<% @month_mins=@month_mins+@mins %>
		<% end %>

<div class="report_entry row">
	<div class="project span2"> <%= @projectname %> </div>
	<div class="mins span2"> <%= @month_mins %> </div>
</div>

<% end %>

app/views/team/index.html.erb
<h1> My Team </h2>


<%= simple_form_for @user, :url=>create_member_path do |f| %>

<%= f.input :email %>

<%= f.submit %>

<% end %>






<br>
<%= @team.each do |user| %>

		<div class="time_entry row">
			  <b> <div class="email span2"> <%= user.email %></div> </b>
			  
		</div>

<% end %>
		